//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Politech3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int ID_Producto { get; set; }
        public string Nombre { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public int Unidad { get; set; }
        public double Precio { get; set; }
        public string Descripcion_Breve { get; set; }
        public string Descripcion { get; set; }
        public string Caracteristicas1 { get; set; }
        public string Caracteristicas2 { get; set; }
        public string Caracteristicas3 { get; set; }
        public string Caracteristicas4 { get; set; }
        public string Caracteristicas5 { get; set; }
        public string Imagen { get; set; }
    }
}
